version: "3.8"
services:
  php80_add_formrequest_accessor:
    container_name: php80_add_formrequest_accessor
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP80_Dockerfile
    volumes:
      - .:/var/www/html
    init: true
    # restart: unless-stopped
    command: ./.docker/command/test.sh

  php81_add_formrequest_accessor:
    container_name: php81_add_formrequest_accessor
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP81_Dockerfile
    volumes:
      - .:/var/www/html
    init: true
    # restart: unless-stopped
    command: ./.docker/command/test.sh
    depends_on:
      - php80_add_formrequest_accessor

  php82_add_formrequest_accessor:
    container_name: php82_add_formrequest_accessor
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP82_Dockerfile
    volumes:
      - .:/var/www/html
    init: true
    # restart: unless-stopped
    command: ./.docker/command/test.sh
    depends_on:
      - php81_add_formrequest_accessor
