version: "3.8"
services:
  #
  php80_add_formrequest_accessor_development:
    container_name: php80_add_formrequest_accessor_development
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP80_Dockerfile
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    init: true
    command: >
      bash -c '
        composer update;
        tail -f /dev/null;
      '
