name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  phpunit:
    uses: ./.github/workflows/phpunit.yml
  static_analysis:
    uses: ./.github/workflows/static_analysis.yml
  slack_notify:
    needs: [phpunit, static_analysis]
    if: ${{ needs.phpunit.result == 'success' && needs.static_analysis.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      uses: ./.github/workflows/pullrequest_notify_slack.yml
