name: PHPUnit test

on:
  workflow_call:

jobs:
  phpunit-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1, 8.2]
        library:
          - { laravel: ^10.0 }
          - { laravel: ^9.0 }
          - { laravel: ^8.0 }
        exclude:
          - { php: 8.0, library: { laravel: ^10.0 } }
          - { php: 8.1, library: { laravel: ^8.0 } }
          - { php: 8.2, library: { laravel: ^8.0 } }

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, zip, xml

    - name: Laravel Install
      run: |
        composer require --dev "laravel/framework:${{ matrix.library.laravel }}"

    - name: Run PHPUnit Test
      run: |
        if [[ ${{ matrix.php }} == "8.1" || ${{ matrix.php }} == "8.2" ]]; then
          vendor/bin/phpunit --migrate-configuration || true
        fi
        vendor/bin/phpunit
