name: Notify pull requests to slack

on:
  pull_request:
    types: [opened, reopened]

jobs:
  slack_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "<!channel>\n${{ github.event.pull_request.user.login }}です。お疲れ様です。\nお手すきの際にレビューお願いいたします。\n\n【${{ github.event.pull_request.title }}】\n${{ github.event.pull_request.html_url }}\n{{- if github.event.pull_request.body != '' -}}```{{ github.event.pull_request.body }}```{{- else -}}\n_（説明文はありません）_\n{{- endif -}}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
