name: Notify pull requests to slack

on:
  pull_request:
    types: [opened]

jobs:
  slack_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "<!channel> \nお疲れ様です\nお手すきの際にレビューお願いいたします\n\n$【{{ github.event.pull_request.title }}】 \n${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
